#ifndef _ARITHMETIC_L_BFGS_B_H_
#define _ARITHMETIC_L_BFGS_B_H_

#include <cstdio>
#include "../../Principle.h"
#include "ap.h"

namespace arithmetic {

class PRINCIPLEDLL L_BFGS_B {
public:
	virtual void funcgrad(const ap::real_1d_array& x, double& f, ap::real_1d_array& g);
	void lbfgsbminimize(const int& n,
		const int& m,
		ap::real_1d_array& x,
		const double& epsg,
		const double& epsf,
		const double& epsx,
		const int& maxits,
		const ap::integer_1d_array& nbd,
		const ap::real_1d_array& l,
		const ap::real_1d_array& u,
		int& info);
	void lbfgsbactive(const int& n,
		const ap::real_1d_array& l,
		const ap::real_1d_array& u,
		const ap::integer_1d_array& nbd,
		ap::real_1d_array& x,
		ap::integer_1d_array& iwhere,
		bool& prjctd,
		bool& cnstnd,
		bool& boxed);
	void lbfgsbbmv(const int& m,
		const ap::real_2d_array& sy,
		ap::real_2d_array& wt,
		const int& col,
		const ap::real_1d_array& v,
		ap::real_1d_array& p,
		int& info,
		ap::real_1d_array& workvec);
	void lbfgsbcauchy(const int& n,
		const ap::real_1d_array& x,
		const ap::real_1d_array& l,
		const ap::real_1d_array& u,
		const ap::integer_1d_array& nbd,
		const ap::real_1d_array& g,
		ap::integer_1d_array& iorder,
		ap::integer_1d_array& iwhere,
		ap::real_1d_array& t,
		ap::real_1d_array& d,
		ap::real_1d_array& xcp,
		const int& m,
		const ap::real_2d_array& wy,
		const ap::real_2d_array& ws,
		const ap::real_2d_array& sy,
		ap::real_2d_array& wt,
		const double& theta,
		const int& col,
		const int& head,
		ap::real_1d_array& p,
		ap::real_1d_array& c,
		ap::real_1d_array& wbp,
		ap::real_1d_array& v,
		int& nint,
		const ap::real_1d_array& sg,
		const ap::real_1d_array& yg,
		const double& sbgnrm,
		int& info,
		ap::real_1d_array& workvec);
	void lbfgsbcmprlb(const int& n,
		const int& m,
		const ap::real_1d_array& x,
		const ap::real_1d_array& g,
		const ap::real_2d_array& ws,
		const ap::real_2d_array& wy,
		const ap::real_2d_array& sy,
		ap::real_2d_array& wt,
		const ap::real_1d_array& z,
		ap::real_1d_array& r,
		ap::real_1d_array& wa,
		const ap::integer_1d_array& index,
		const double& theta,
		const int& col,
		const int& head,
		const int& nfree,
		const bool& cnstnd,
		int& info,
		ap::real_1d_array& workvec,
		ap::real_1d_array& workvec2);
	void lbfgsberrclb(const int& n,
		const int& m,
		const double& factr,
		const ap::real_1d_array& l,
		const ap::real_1d_array& u,
		const ap::integer_1d_array& nbd,
		int& task,
		int& info,
		int& k);
	void lbfgsbformk(const int& n,
		const int& nsub,
		const ap::integer_1d_array& ind,
		const int& nenter,
		const int& ileave,
		const ap::integer_1d_array& indx2,
		const int& iupdat,
		const bool& updatd,
		ap::real_2d_array& wn,
		ap::real_2d_array& wn1,
		const int& m,
		const ap::real_2d_array& ws,
		const ap::real_2d_array& wy,
		const ap::real_2d_array& sy,
		const double& theta,
		const int& col,
		const int& head,
		int& info,
		ap::real_1d_array& workvec,
		ap::real_2d_array& workmat);
	void lbfgsbformt(const int& m,
		ap::real_2d_array& wt,
		const ap::real_2d_array& sy,
		const ap::real_2d_array& ss,
		const int& col,
		const double& theta,
		int& info);
	void lbfgsbfreev(const int& n,
		int& nfree,
		ap::integer_1d_array& index,
		int& nenter,
		int& ileave,
		ap::integer_1d_array& indx2,
		const ap::integer_1d_array& iwhere,
		bool& wrk,
		const bool& updatd,
		const bool& cnstnd,
		const int& iter);
	void lbfgsbhpsolb(const int& n,
		ap::real_1d_array& t,
		ap::integer_1d_array& iorder,
		const int& iheap);
	void lbfgsblnsrlb(const int& n,
		const ap::real_1d_array& l,
		const ap::real_1d_array& u,
		const ap::integer_1d_array& nbd,
		ap::real_1d_array& x,
		const double& f,
		double& fold,
		double& gd,
		double& gdold,
		const ap::real_1d_array& g,
		const ap::real_1d_array& d,
		ap::real_1d_array& r,
		ap::real_1d_array& t,
		const ap::real_1d_array& z,
		double& stp,
		double& dnrm,
		double& dtd,
		double& xstep,
		double& stpmx,
		const int& iter,
		int& ifun,
		int& iback,
		int& nfgv,
		int& info,
		int& task,
		const bool& boxed,
		const bool& cnstnd,
		int& csave,
		ap::integer_1d_array& isave,
		ap::real_1d_array& dsave);
	void lbfgsbmatupd(const int& n,
		const int& m,
		ap::real_2d_array& ws,
		ap::real_2d_array& wy,
		ap::real_2d_array& sy,
		ap::real_2d_array& ss,
		const ap::real_1d_array& d,
		const ap::real_1d_array& r,
		int& itail,
		const int& iupdat,
		int& col,
		int& head,
		double& theta,
		const double& rr,
		const double& dr,
		const double& stp,
		const double& dtd);
	void lbfgsbprojgr(const int& n,
		const ap::real_1d_array& l,
		const ap::real_1d_array& u,
		const ap::integer_1d_array& nbd,
		const ap::real_1d_array& x,
		const ap::real_1d_array& g,
		double& sbgnrm);
	void lbfgsbsubsm(const int& n,
		const int& m,
		const int& nsub,
		const ap::integer_1d_array& ind,
		const ap::real_1d_array& l,
		const ap::real_1d_array& u,
		const ap::integer_1d_array& nbd,
		ap::real_1d_array& x,
		ap::real_1d_array& d,
		const ap::real_2d_array& ws,
		const ap::real_2d_array& wy,
		const double& theta,
		const int& col,
		const int& head,
		int& iword,
		ap::real_1d_array& wv,
		ap::real_2d_array& wn,
		int& info);
	void lbfgsbdcsrch(const double& f,
		const double& g,
		double& stp,
		const double& ftol,
		const double& gtol,
		const double& xtol,
		const double& stpmin,
		const double& stpmax,
		int& task,
		ap::integer_1d_array& isave,
		ap::real_1d_array& dsave,
		int& addinfo);
	void lbfgsbdcstep(double& stx,
		double& fx,
		double& dx,
		double& sty,
		double& fy,
		double& dy,
		double& stp,
		const double& fp,
		const double& dp,
		bool& brackt,
		const double& stpmin,
		const double& stpmax);
	bool additionallbfgsbstoppingcriterion(int iter,
		const ap::real_1d_array& x,
		double f,
		const ap::real_1d_array& g);
	bool lbfgsbdpofa(ap::real_2d_array& a, const int& n);
	void lbfgsbdtrsl(ap::real_2d_array& t,
		const int& n,
		ap::real_1d_array& b,
		const int& job,
		int& info);
	void lbfgsbnewiteration(const ap::real_1d_array& x,
		double f,
		const ap::real_1d_array& g);

private:
};

};		// arithmetic

#endif